language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: setup=lowest
    - php: 7.2
    - php: 7.2
      env: setup=lowest
    - php: 7.3
    - php: 7.3
      env: setup=lowest

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install

script:
  - phpunit
